//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndComedoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comedor
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Pais { get; set; }
        public string Departamento { get; set; }
        public string Ciudad { get; set; }
        public string Contacto { get; set; }
        public string Email_Contacto { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Numero_Niños { get; set; }
        public Nullable<System.TimeSpan> ZonaHorarioRecepción { get; set; }
    }
}
