//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndComedoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad
    {
        public int IDProveedor { get; set; }
        public int ID { get; set; }
        public int IDProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Valor_Unitario { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
