//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndComedoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public string Preservación { get; set; }
        public string Unidad_Medida { get; set; }
    
        public virtual Disponibilidad Disponibilidad { get; set; }
        public virtual Ingrediente Ingrediente { get; set; }
    }
}
