//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndComedoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Placas { get; set; }
        public string Marca { get; set; }
        public string Anio { get; set; }
        public string Tipo_Transporte { get; set; }
        public string Encargado { get; set; }
        public string Telefono_Encargardo { get; set; }
        public string Email_Encargado { get; set; }
        public string Tipo_Cobro { get; set; }
        public string Unidad_Cobro { get; set; }
        public Nullable<decimal> Medida_cobro { get; set; }
        public Nullable<decimal> Valor_cobro { get; set; }
        public Nullable<bool> Disponible { get; set; }
    }
}
