//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndComedores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibility
    {
        public Nullable<long> IDProvider { get; set; }
        public long ID { get; set; }
        public Nullable<long> IDProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitValue { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Product Product { get; set; }
    }
}
