//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndComedores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Neiborhood { get; set; }
        public string City { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Contact { get; set; }
        public Nullable<long> ContactPhone { get; set; }
        public string ContactMail { get; set; }
        public string EnterpriseMail { get; set; }
        public string NIT { get; set; }
        public string Type { get; set; }
    }
}
